In [1]:
import numpy as np

In [ ]:
printing of Numpy arrays

In [2]:
a =np.arange(6)

In [3]:
print(a)

[0 1 2 3 4 5]


In [4]:
type(a)

numpy.ndarray

In [ ]:
2D array

In [5]:
b =  np.arange(12).reshape(4,3)

print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
3D Array

In [6]:
c = np.arange(24).reshape(2,3,4) #3D

print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
Introduction to statistical concepts:

In [9]:
test_scores = np.array([32.32,56.98,21.52,44.32,55.63,13.75,43.47,34])

In [10]:
print('Mean test scores are below for give scores:')
print(np.mean(test_scores))

Mean test scores are below for give scores:
37.74875


In [11]:
print("Median test scores of the students")

print(np.median(test_scores))

Median test scores of the students
38.735
