In [1]:
import numpy as np

In [ ]:
# Basic operations in numpy

In [2]:
a = np.array([10,10,10])

b = np.array([5,5,5])

In [3]:
a+b

array([15, 15, 15])

In [4]:
a-b

array([5, 5, 5])

In [5]:
a*b

array([50, 50, 50])

In [6]:
a/b #why are we receiving 2. ---> point to decimal

array([2., 2., 2.])

In [7]:
a%b #modulous operator -->reminder

array([0, 0, 0], dtype=int32)

In [8]:
a%3

array([1, 1, 1], dtype=int32)

In [ ]:
comparision operators:

In [9]:
a<30 #10<30

array([ True,  True,  True])

In [10]:
a>30

array([False, False, False])

In [11]:
a**2

array([100, 100, 100], dtype=int32)

In [12]:
a**3

array([1000, 1000, 1000], dtype=int32)

In [ ]:
#Req: how to modify an existing array

In [13]:
a +=3
a

array([13, 13, 13])

In [14]:
b +=a

In [15]:
b

array([18, 18, 18])

In [ ]:
#unary operators

In [16]:
ages = np.array([12,15,18,20])

In [17]:
ages.sum()

65

In [18]:
ages.min()

12

In [19]:
ages.max()

20

In [21]:
numbers = np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
print(numbers)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
